/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Student;

import UI.EmployerJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author kanad
 */
public class StudentoptionsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentSubjectsFeeJPanel
     */
    private JPanel pnlWorkSystem; 
    public StudentoptionsJPanel(JPanel pnlWorkSystem) {
        initComponents();
        this.pnlWorkSystem = pnlWorkSystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btncoursecat = new javax.swing.JButton();
        btntranscrips = new javax.swing.JButton();
        lblStudentlobbytitle = new javax.swing.JLabel();
        lblcoursecatalog = new javax.swing.JLabel();
        lbltranscript = new javax.swing.JLabel();

        btncoursecat.setText("Course catalog");
        btncoursecat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncoursecatActionPerformed(evt);
            }
        });

        btntranscrips.setText("transcripts");
        btntranscrips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntranscripsActionPerformed(evt);
            }
        });

        lblStudentlobbytitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblStudentlobbytitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStudentlobbytitle.setText("Student Lobby");

        lblcoursecatalog.setText("Select Course : ");

        lbltranscript.setText("Final Transcript :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStudentlobbytitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblcoursecatalog)
                    .addComponent(lbltranscript))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btncoursecat, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(btntranscrips, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblStudentlobbytitle)
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncoursecat)
                    .addComponent(lblcoursecatalog))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntranscrips)
                    .addComponent(lbltranscript))
                .addContainerGap(356, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btncoursecatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncoursecatActionPerformed
        // TODO add your handling code here:
        CourseJPanel cojp = new CourseJPanel(pnlWorkSystem);
        pnlWorkSystem.add("CourseJPanel",cojp);
        CardLayout layout = (CardLayout)pnlWorkSystem.getLayout();
        layout.next(pnlWorkSystem);
    }//GEN-LAST:event_btncoursecatActionPerformed

    private void btntranscripsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntranscripsActionPerformed
        // TODO add your handling code here:
        TranscriptJPanel tjp = new TranscriptJPanel(pnlWorkSystem);
        pnlWorkSystem.add("TranscriptJPanel",tjp);
         CardLayout layout = (CardLayout)pnlWorkSystem.getLayout();
        layout.next(pnlWorkSystem);
    }//GEN-LAST:event_btntranscripsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncoursecat;
    private javax.swing.JButton btntranscrips;
    private javax.swing.JLabel lblStudentlobbytitle;
    private javax.swing.JLabel lblcoursecatalog;
    private javax.swing.JLabel lbltranscript;
    // End of variables declaration//GEN-END:variables
}
