/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import UI.Admin.AdminLobbyJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author kanad
 */
public class AdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminJPanel
     */
    JPanel pnlWorkSystem;
    public AdminJPanel(JPanel pnlWorkSystem) {
        initComponents();
        this.pnlWorkSystem = pnlWorkSystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdminID = new javax.swing.JLabel();
        lblAdminPass = new javax.swing.JLabel();
        txtAdminID = new javax.swing.JTextField();
        txtAdminPass = new javax.swing.JTextField();
        btnConfirmAdmin = new javax.swing.JButton();
        lblAdminTitle1 = new javax.swing.JLabel();

        lblAdminID.setText("Admin ID:");

        lblAdminPass.setText("Password :");

        btnConfirmAdmin.setText("Confirm");
        btnConfirmAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmAdminActionPerformed(evt);
            }
        });

        lblAdminTitle1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAdminTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdminTitle1.setText("Admin Login ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAdminTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAdminID)
                                    .addComponent(lblAdminPass))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAdminID, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAdminPass, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(258, 258, 258)
                                .addComponent(btnConfirmAdmin)))
                        .addGap(0, 147, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblAdminTitle1)
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminID)
                    .addComponent(txtAdminID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminPass)
                    .addComponent(txtAdminPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnConfirmAdmin)
                .addContainerGap(312, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmAdminActionPerformed
        // TODO add your handling code here:
        AdminLobbyJPanel aljp = new AdminLobbyJPanel(pnlWorkSystem);
        pnlWorkSystem.add("AdminLobbyJPanel",aljp);
        CardLayout layout = (CardLayout)pnlWorkSystem.getLayout();
        layout.next(pnlWorkSystem);
        
        
    }//GEN-LAST:event_btnConfirmAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmAdmin;
    private javax.swing.JLabel lblAdminID;
    private javax.swing.JLabel lblAdminPass;
    private javax.swing.JLabel lblAdminTitle1;
    private javax.swing.JTextField txtAdminID;
    private javax.swing.JTextField txtAdminPass;
    // End of variables declaration//GEN-END:variables
}
