/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import UI.Faculty.FacultyWorkJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author kanad
 */
public class FacultyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FacultyJPanel
     */
    private JPanel pnlWorkSystem;
    public FacultyJPanel(JPanel pnlWorkSystem) {
        initComponents();
        this.pnlWorkSystem = pnlWorkSystem;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFacultyPass1 = new javax.swing.JLabel();
        txtFacultyID = new javax.swing.JTextField();
        txtFacultyPass = new javax.swing.JTextField();
        btnConfirmFaculty1 = new javax.swing.JButton();
        lblFacultyTitle2 = new javax.swing.JLabel();
        lblFacultyID = new javax.swing.JLabel();

        lblFacultyPass1.setText("Password :");

        btnConfirmFaculty1.setText("Confirm");
        btnConfirmFaculty1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmFaculty1ActionPerformed(evt);
            }
        });

        lblFacultyTitle2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFacultyTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFacultyTitle2.setText("Faculty Login ");

        lblFacultyID.setText("Admin ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFacultyTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblFacultyID)
                                    .addComponent(lblFacultyPass1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFacultyID, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFacultyPass, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(258, 258, 258)
                                .addComponent(btnConfirmFaculty1)))
                        .addGap(0, 147, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblFacultyTitle2)
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFacultyID)
                    .addComponent(txtFacultyID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFacultyPass1)
                    .addComponent(txtFacultyPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnConfirmFaculty1)
                .addContainerGap(312, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmFaculty1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmFaculty1ActionPerformed
        // TODO add your handling code here:
        FacultyWorkJPanel awajp = new FacultyWorkJPanel(pnlWorkSystem);
        pnlWorkSystem.add("FacultyWorkJPanel",awajp);
        CardLayout layout = (CardLayout)pnlWorkSystem.getLayout();
        layout.next(pnlWorkSystem);
    }//GEN-LAST:event_btnConfirmFaculty1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmFaculty1;
    private javax.swing.JLabel lblFacultyID;
    private javax.swing.JLabel lblFacultyPass1;
    private javax.swing.JLabel lblFacultyTitle2;
    private javax.swing.JTextField txtFacultyID;
    private javax.swing.JTextField txtFacultyPass;
    // End of variables declaration//GEN-END:variables
}
