/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Alumini.AluminiHistory;
import java.awt.CardLayout;

/**
 *
 * @author kanad
 */
public class mainJFrame extends javax.swing.JFrame {


    

    /**
     * Creates new form mainJFrame
     */
    AluminiHistory history;
    public mainJFrame() {
        initComponents();
        history = new AluminiHistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        pnlWorkarea = new javax.swing.JPanel();
        btnStudent = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        btnFaculty = new javax.swing.JButton();
        btnEmployer = new javax.swing.JButton();
        btnAlumini = new javax.swing.JButton();
        pnlWorkSystem = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStudent.setText("Student");
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentActionPerformed(evt);
            }
        });

        btnAdmin.setText("Admin");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        btnFaculty.setText("Faculty");
        btnFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacultyActionPerformed(evt);
            }
        });

        btnEmployer.setText("Employer");
        btnEmployer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployerActionPerformed(evt);
            }
        });

        btnAlumini.setText("Alumini");
        btnAlumini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAluminiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlWorkareaLayout = new javax.swing.GroupLayout(pnlWorkarea);
        pnlWorkarea.setLayout(pnlWorkareaLayout);
        pnlWorkareaLayout.setHorizontalGroup(
            pnlWorkareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWorkareaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlWorkareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmployer, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlumini, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlWorkareaLayout.setVerticalGroup(
            pnlWorkareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWorkareaLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnStudent)
                .addGap(18, 18, 18)
                .addComponent(btnAdmin)
                .addGap(18, 18, 18)
                .addComponent(btnFaculty)
                .addGap(18, 18, 18)
                .addComponent(btnEmployer)
                .addGap(18, 18, 18)
                .addComponent(btnAlumini)
                .addContainerGap(360, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(pnlWorkarea);

        pnlWorkSystem.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(pnlWorkSystem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
        

        // TODO add your handling code here:
        StudentJPanel sjp = new StudentJPanel(pnlWorkSystem);
        pnlWorkSystem.add("StudentJPanel",sjp);
        CardLayout layout = (CardLayout)pnlWorkSystem.getLayout();
        layout.next(pnlWorkSystem);
        
        
        
        
        
    }//GEN-LAST:event_btnStudentActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
        AdminJPanel ajp = new AdminJPanel(pnlWorkSystem);
        pnlWorkSystem.add("AdminJpanel",ajp);
        CardLayout layout = (CardLayout)pnlWorkSystem.getLayout();
        layout.next(pnlWorkSystem);

        
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacultyActionPerformed
        // TODO add your handling code here:
        FacultyJPanel fjp = new FacultyJPanel(pnlWorkSystem);
        pnlWorkSystem.add("FacultyJpanel",fjp);
        CardLayout layout = (CardLayout)pnlWorkSystem.getLayout();
        layout.next(pnlWorkSystem);
        
        
    }//GEN-LAST:event_btnFacultyActionPerformed

    private void btnEmployerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployerActionPerformed
        // TODO add your handling code here:
        EmployerJPanel ejp = new EmployerJPanel(pnlWorkSystem);
        pnlWorkSystem.add("EmployerJpanel",ejp);
        CardLayout layout = (CardLayout)pnlWorkSystem.getLayout();
        layout.next(pnlWorkSystem);
    }//GEN-LAST:event_btnEmployerActionPerformed

    private void btnAluminiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAluminiActionPerformed
        // TODO add your handling code here:
        AluminiJPanel aluminiJpanel = new AluminiJPanel(history);
        jSplitPane1.setRightComponent(aluminiJpanel);
    }//GEN-LAST:event_btnAluminiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnAlumini;
    private javax.swing.JButton btnEmployer;
    private javax.swing.JButton btnFaculty;
    private javax.swing.JButton btnStudent;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel pnlWorkSystem;
    private javax.swing.JPanel pnlWorkarea;
    // End of variables declaration//GEN-END:variables
}
